spring:
  datasource:
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lanqiao?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    initialization-mode: embedded
    type: com.alibaba.druid.pool.DruidDataSource
    maxActive: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml